import Script from "next/script";
import "./globals.css";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <head>
        <Script
          async
          id="cookieyes"
          type="text/javascript"
          src="https://cdn-cookieyes.com/client_data/2b6b0ab2b70ad7a6db85e0c8/script.js"
        ></Script>
      </head>
      <html lang="en">
        <body className={`font-gilroy bg-[#ebebef]`}>{children}</body>
      </html>
    </>
  );
}
