import Script from "next/script";
import "./globals.css";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <head>
      </head>
      <html lang="en">
        <body className={`font-gilroy bg-[#ebebef]`}>{children}</body>
      </html>
    </>
  );
}
